spring:
  application:
    name: gateway
  cloud:
    # 网关配置
    gateway:
      discovery:
        locator:
          # 是否开启自动根据注册中心ID路由转发
          enabled: true
          lowerCaseServiceId: true
#      routes:
#        # This route rule used to forward request to activity server
#        - id: SEVICE-USER
#          uri: lb://SEVICE-USER
#          predicates:
#            - Path=/api-product/**
#          filters:
#            - StripPrefix=1