server:
  port: 8761
eureka:
  instance:
    hostname: reg-beta-001.inner.jinrinsh.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka



