server:
  port: 8082

spring:
  application:
    name: service-user
  zipkin:
#    zipkin服务地址
    base-url: http://localhost:8768
    sleuth:
      sampler:
#        采集率
      percentage: 1.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


